=== Gabriel-Benoit/EzInvoiceRS/json-schema/schema/InvoiceData.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "additionalProperties": false,
    "definitions": {
        "Adress": {
            "additionalProperties": false,
            "properties": {
                "city": {
                    "type": "string"
                },
                "num": {
                    "type": "string"
                },
                "numSuffix": {
                    "type": "string"
                },
                "postCode": {
                    "type": "string"
                },
                "street": {
                    "type": "string"
                }
            },
            "required": [
                "city",
                "num",
                "postCode",
                "street"
            ],
            "type": "object"
        },
        "Buyer": {
            "$ref": "#/definitions/Entity"
        },
        "Entity": {
            "additionalProperties": false,
            "properties": {
                "adress": {
                    "$ref": "#/definitions/Adress"
                },
                "name": {
                    "type": "string"
                },
                "vatNumber": {
                    "type": "string"
                }
            },
            "required": [
                "adress",
                "name",
                "vatNumber"
            ],
            "type": "object"
        },
        "Entreprise": {
            "additionalProperties": false,
            "properties": {
                "adress": {
                    "$ref": "#/definitions/Adress"
                },
                "email": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "vatNumber": {
                    "type": "string"
                },
                "website": {
                    "type": "string"
                }
            },
            "required": [
                "adress",
                "email",
                "name",
                "phone",
                "vatNumber",
                "website"
            ],
            "type": "object"
        },
        "Item": {
            "additionalProperties": false,
            "properties": {
                "description": {
                    "type": "string"
                },
                "intra": {
                    "type": "boolean"
                },
                "priceHT": {
                    "type": "number"
                },
                "qt": {
                    "type": "number"
                },
                "vat": {
                    "enum": [
                        "12.0",
                        "21.0",
                        "6.0"
                    ],
                    "type": "string"
                }
            },
            "required": [
                "description",
                "intra",
                "priceHT",
                "qt",
                "vat"
            ],
            "type": "object"
        }
    },
    "properties": {
        "billNumber": {
            "type": "number"
        },
        "buyer": {
            "$ref": "#/definitions/Buyer"
        },
        "date": {
            "type": "string"
        },
        "duePercentage": {
            "type": "number"
        },
        "duration": {
            "type": "number"
        },
        "entreprise": {
            "$ref": "#/definitions/Entreprise"
        },
        "items": {
            "items": {
                "$ref": "#/definitions/Item"
            },
            "type": "array"
        },
        "logoURL": {
            "type": "string"
        },
        "structuredCommunication": {
            "type": "string"
        },
        "title": {
            "type": "string"
        }
    },
    "required": [
        "billNumber",
        "buyer",
        "date",
        "duePercentage",
        "duration",
        "entreprise",
        "items",
        "logoURL",
        "structuredCommunication",
        "title"
    ],
    "type": "object"
}

=== Gabriel-Benoit/EzInvoiceRS/json-schema/mock.json
{
	"items": [],
	"billNumber": 0,
	"buyer": {
		"adress": {
			"num": "",
			"numSuffix": "",
			"city": "",
			"street": "",
			"postCode": ""
		},
		"name": "",
		"vatNumber": ""
	},
	"entreprise": {
		"phone": "",
		"email": "",
		"adress": {
			"num": "",
			"numSuffix": "",
			"city": "",
			"street": "",
			"postCode": ""
		},
		"name": "",
		"vatNumber": "",
		"website": "it works"
	},
	"title": "",
	"date": "",
	"duration": 0,
	"logoURL": "coucou.com",
	"duePercentage": 0,
	"structuredCommunication": ""
}
